function [blanco, N, modF]=BlancosAcelerados(~)
 N=2;
 modF=2;
 blanco=cell(1,N);
 %% Blanco 1
 blanco{1}.modo=9;
 x_ini=8000;
 y_ini=-6500;
 z_ini=0;
 pos_ini=cart2esf([x_ini y_ini z_ini]);
 blanco{1}.r_i=pos_ini(1);
 blanco{1}.phi_i=pos_ini(2);
 blanco{1}.theta_i=pos_ini(3);
 blanco{1}.v=50;
 blanco{1}.w=0.05*2*pi;
 blanco{1}.vectorVel(1)=-5;
 blanco{1}.vectorVel(2)=-5;
 blanco{1}.vectorVel(3)=5;
 blanco{1}.modVel=rssq(blanco{1}.vectorVel);
 blanco{1}.escala=0.5/10;
 blanco{1}.vectorAcc=blanco{1}.escala*blanco{1}.vectorVel;
 blanco{1}.mode=1;
 %% Blanco 2 
  blanco{2}.modo=9;
 x_ini=-8000;
 y_ini=+6500;
 z_ini=2000;
 pos_ini=cart2esf([x_ini y_ini z_ini]);
 blanco{2}.r_i=pos_ini(1);
 blanco{2}.phi_i=pos_ini(2);
 blanco{2}.theta_i=pos_ini(3);
 blanco{2}.v=50;
 blanco{2}.w=0.05*2*pi;
 blanco{2}.vectorVel(1)=+5;
 blanco{2}.vectorVel(2)=+5;
 blanco{2}.vectorVel(3)=-5;
 blanco{2}.modVel=rssq(blanco{1}.vectorVel);
 blanco{2}.escala=0.5/50;
 blanco{2}.vectorAcc=blanco{2}.escala*blanco{2}.vectorVel;
 blanco{2}.mode=1;
end 